// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package generics

import (
	"context"
	"sync"
)

// Ensure, that GenericStore1Mock does implement GenericStore1.
// If this is not the case, regenerate this file with moq.
var _ GenericStore1[Key1, any] = &GenericStore1Mock[Key1, any]{}

// GenericStore1Mock is a mock implementation of GenericStore1.
//
//	func TestSomethingThatUsesGenericStore1(t *testing.T) {
//
//		// make and configure a mocked GenericStore1
//		mockedGenericStore1 := &GenericStore1Mock{
//			CreateFunc: func(ctx context.Context, id T, value S) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id T) (S, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedGenericStore1 in code that requires GenericStore1
//		// and then make assertions.
//
//	}

type GenericStore1Mock[T Key1, S any] struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, id T, value S) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id T) (S, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []GenericStore1MockCreateCalls[T, S]
		// Get holds details about calls to the Get method.
		Get []GenericStore1MockGetCalls[T, S]
	}
	lockCreate sync.RWMutex
	lockGet    sync.RWMutex
}

// GenericStore1MockCreateCalls holds details about calls to the Create method.
type GenericStore1MockCreateCalls[T Key1, S any] struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID T
	// Value is the value argument value.
	Value S
}

// GenericStore1MockGetCalls holds details about calls to the Get method.
type GenericStore1MockGetCalls[T Key1, S any] struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID T
}

// Create calls CreateFunc.
func (mock *GenericStore1Mock[T, S]) Create(ctx context.Context, id T, value S) error {
	if mock.CreateFunc == nil {
		panic("GenericStore1Mock.CreateFunc: method is nil but GenericStore1.Create was just called")
	}
	callInfo := GenericStore1MockCreateCalls[T, S]{
		Ctx:   ctx,
		ID:    id,
		Value: value,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, id, value)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedGenericStore1.CreateCalls())
func (mock *GenericStore1Mock[T, S]) CreateCalls() []GenericStore1MockCreateCalls[T, S] {
	var calls []GenericStore1MockCreateCalls[T, S]
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *GenericStore1Mock[T, S]) Get(ctx context.Context, id T) (S, error) {
	if mock.GetFunc == nil {
		panic("GenericStore1Mock.GetFunc: method is nil but GenericStore1.Get was just called")
	}
	callInfo := GenericStore1MockGetCalls[T, S]{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGenericStore1.GetCalls())
func (mock *GenericStore1Mock[T, S]) GetCalls() []GenericStore1MockGetCalls[T, S] {
	var calls []GenericStore1MockGetCalls[T, S]
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Ensure, that GenericStore2Mock does implement GenericStore2.
// If this is not the case, regenerate this file with moq.
var _ GenericStore2[[]byte, any] = &GenericStore2Mock[[]byte, any]{}

// GenericStore2Mock is a mock implementation of GenericStore2.
//
//	func TestSomethingThatUsesGenericStore2(t *testing.T) {
//
//		// make and configure a mocked GenericStore2
//		mockedGenericStore2 := &GenericStore2Mock{
//			CreateFunc: func(ctx context.Context, id T, value S) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id T) (S, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedGenericStore2 in code that requires GenericStore2
//		// and then make assertions.
//
//	}

type GenericStore2Mock[T Key2, S any] struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, id T, value S) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id T) (S, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []GenericStore2MockCreateCalls[T, S]
		// Get holds details about calls to the Get method.
		Get []GenericStore2MockGetCalls[T, S]
	}
	lockCreate sync.RWMutex
	lockGet    sync.RWMutex
}

// GenericStore2MockCreateCalls holds details about calls to the Create method.
type GenericStore2MockCreateCalls[T Key2, S any] struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID T
	// Value is the value argument value.
	Value S
}

// GenericStore2MockGetCalls holds details about calls to the Get method.
type GenericStore2MockGetCalls[T Key2, S any] struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID T
}

// Create calls CreateFunc.
func (mock *GenericStore2Mock[T, S]) Create(ctx context.Context, id T, value S) error {
	if mock.CreateFunc == nil {
		panic("GenericStore2Mock.CreateFunc: method is nil but GenericStore2.Create was just called")
	}
	callInfo := GenericStore2MockCreateCalls[T, S]{
		Ctx:   ctx,
		ID:    id,
		Value: value,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, id, value)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedGenericStore2.CreateCalls())
func (mock *GenericStore2Mock[T, S]) CreateCalls() []GenericStore2MockCreateCalls[T, S] {
	var calls []GenericStore2MockCreateCalls[T, S]
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *GenericStore2Mock[T, S]) Get(ctx context.Context, id T) (S, error) {
	if mock.GetFunc == nil {
		panic("GenericStore2Mock.GetFunc: method is nil but GenericStore2.Get was just called")
	}
	callInfo := GenericStore2MockGetCalls[T, S]{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGenericStore2.GetCalls())
func (mock *GenericStore2Mock[T, S]) GetCalls() []GenericStore2MockGetCalls[T, S] {
	var calls []GenericStore2MockGetCalls[T, S]
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Ensure, that AliasStoreMock does implement AliasStore.
// If this is not the case, regenerate this file with moq.
var _ AliasStore = &AliasStoreMock{}

// AliasStoreMock is a mock implementation of AliasStore.
//
//	func TestSomethingThatUsesAliasStore(t *testing.T) {
//
//		// make and configure a mocked AliasStore
//		mockedAliasStore := &AliasStoreMock{
//			CreateFunc: func(ctx context.Context, id KeyImpl, value bool) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id KeyImpl) (bool, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedAliasStore in code that requires AliasStore
//		// and then make assertions.
//
//	}

type AliasStoreMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, id KeyImpl, value bool) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id KeyImpl) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []AliasStoreMockCreateCalls
		// Get holds details about calls to the Get method.
		Get []AliasStoreMockGetCalls
	}
	lockCreate sync.RWMutex
	lockGet    sync.RWMutex
}

// AliasStoreMockCreateCalls holds details about calls to the Create method.
type AliasStoreMockCreateCalls struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID KeyImpl
	// Value is the value argument value.
	Value bool
}

// AliasStoreMockGetCalls holds details about calls to the Get method.
type AliasStoreMockGetCalls struct {
	// Ctx is the ctx argument value.
	Ctx context.Context
	// ID is the id argument value.
	ID KeyImpl
}

// Create calls CreateFunc.
func (mock *AliasStoreMock) Create(ctx context.Context, id KeyImpl, value bool) error {
	if mock.CreateFunc == nil {
		panic("AliasStoreMock.CreateFunc: method is nil but AliasStore.Create was just called")
	}
	callInfo := AliasStoreMockCreateCalls{
		Ctx:   ctx,
		ID:    id,
		Value: value,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, id, value)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAliasStore.CreateCalls())
func (mock *AliasStoreMock) CreateCalls() []AliasStoreMockCreateCalls {
	var calls []AliasStoreMockCreateCalls
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *AliasStoreMock) Get(ctx context.Context, id KeyImpl) (bool, error) {
	if mock.GetFunc == nil {
		panic("AliasStoreMock.GetFunc: method is nil but AliasStore.Get was just called")
	}
	callInfo := AliasStoreMockGetCalls{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedAliasStore.GetCalls())
func (mock *AliasStoreMock) GetCalls() []AliasStoreMockGetCalls {
	var calls []AliasStoreMockGetCalls
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
