// Code generated by moq; DO NOT EDIT.
// github.com/rewardStyle/moq

package user

import (
	"github.com/sudo-suhas/moq-test-pkgs/somerepo"
	"sync"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
// 	func TestSomethingThatUsesService(t *testing.T) {
//
// 		// make and configure a mocked Service
// 		mockedService := &ServiceMock{
// 			DoSomethingFunc: func(someType somerepo.SomeType) error {
// 				panic("mock out the DoSomething method")
// 			},
// 		}
//
// 		// use mockedService in code that requires Service
// 		// and then make assertions.
//
// 	}
type ServiceMock struct {
	// DoSomethingFunc mocks the DoSomething method.
	DoSomethingFunc func(someType somerepo.SomeType) error

	// calls tracks calls to the methods.
	calls struct {
		// DoSomething holds details about calls to the DoSomething method.
		DoSomething []struct {
			// SomeType is the someType argument value.
			SomeType somerepo.SomeType
		}
	}
	lockDoSomething sync.RWMutex
}

// DoSomething calls DoSomethingFunc.
func (mock *ServiceMock) DoSomething(someType somerepo.SomeType) error {
	if mock.DoSomethingFunc == nil {
		panic("ServiceMock.DoSomethingFunc: method is nil but Service.DoSomething was just called")
	}
	callInfo := struct {
		SomeType somerepo.SomeType
	}{
		SomeType: someType,
	}
	mock.lockDoSomething.Lock()
	mock.calls.DoSomething = append(mock.calls.DoSomething, callInfo)
	mock.lockDoSomething.Unlock()
	return mock.DoSomethingFunc(someType)
}

// DoSomethingCalls gets all the calls that were made to DoSomething.
// Check the length with:
//     len(mockedService.DoSomethingCalls())
func (mock *ServiceMock) DoSomethingCalls() []struct {
	SomeType somerepo.SomeType
} {
	var calls []struct {
		SomeType somerepo.SomeType
	}
	mock.lockDoSomething.RLock()
	calls = mock.calls.DoSomething
	mock.lockDoSomething.RUnlock()
	return calls
}
