// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/matryer/moq/pkg/moq/testpackages/embedtypes"
	"sync"
)

// Ensure, that Interface1Mock does implement embedtypes.Interface1.
// If this is not the case, regenerate this file with moq.
var _ embedtypes.Interface1 = &Interface1Mock{}

// Interface1Mock is a mock implementation of embedtypes.Interface1.
//
//	func TestSomethingThatUsesInterface1(t *testing.T) {
//
//		// make and configure a mocked embedtypes.Interface1
//		mockedInterface1 := &Interface1Mock{
//			ExportedMethodFunc: func()  {
//				panic("mock out the ExportedMethod method")
//			},
//		}
//
//		// use mockedInterface1 in code that requires embedtypes.Interface1
//		// and then make assertions.
//
//	}
type Interface1Mock struct {
	embedtypes.Embedded1

	// ExportedMethodFunc mocks the ExportedMethod method.
	ExportedMethodFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// ExportedMethod holds details about calls to the ExportedMethod method.
		ExportedMethod []struct {
		}
	}
	lockExportedMethod sync.RWMutex
}

// ExportedMethod calls ExportedMethodFunc.
func (mock *Interface1Mock) ExportedMethod() {
	if mock.ExportedMethodFunc == nil {
		panic("Interface1Mock.ExportedMethodFunc: method is nil but Interface1.ExportedMethod was just called")
	}
	callInfo := struct {
	}{}
	mock.lockExportedMethod.Lock()
	mock.calls.ExportedMethod = append(mock.calls.ExportedMethod, callInfo)
	mock.lockExportedMethod.Unlock()
	mock.ExportedMethodFunc()
}

// ExportedMethodCalls gets all the calls that were made to ExportedMethod.
// Check the length with:
//
//	len(mockedInterface1.ExportedMethodCalls())
func (mock *Interface1Mock) ExportedMethodCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockExportedMethod.RLock()
	calls = mock.calls.ExportedMethod
	mock.lockExportedMethod.RUnlock()
	return calls
}
