// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/matryer/moq/pkg/moq/testpackages/embedtypes"
	"sync"
)

// Ensure, that Interface2Mock does implement embedtypes.Interface2.
// If this is not the case, regenerate this file with moq.
var _ embedtypes.Interface2 = &Interface2Mock{}

// Interface2Mock is a mock implementation of embedtypes.Interface2.
//
//	func TestSomethingThatUsesInterface2(t *testing.T) {
//
//		// make and configure a mocked embedtypes.Interface2
//		mockedInterface2 := &Interface2Mock{
//			ExportedMethodFunc: func()  {
//				panic("mock out the ExportedMethod method")
//			},
//		}
//
//		// use mockedInterface2 in code that requires embedtypes.Interface2
//		// and then make assertions.
//
//	}
type Interface2Mock struct {
	*embedtypes.Embedded2

	// ExportedMethodFunc mocks the ExportedMethod method.
	ExportedMethodFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// ExportedMethod holds details about calls to the ExportedMethod method.
		ExportedMethod []struct {
		}
	}
	lockExportedMethod sync.RWMutex
}

// ExportedMethod calls ExportedMethodFunc.
func (mock *Interface2Mock) ExportedMethod() {
	if mock.ExportedMethodFunc == nil {
		panic("Interface2Mock.ExportedMethodFunc: method is nil but Interface2.ExportedMethod was just called")
	}
	callInfo := struct {
	}{}
	mock.lockExportedMethod.Lock()
	mock.calls.ExportedMethod = append(mock.calls.ExportedMethod, callInfo)
	mock.lockExportedMethod.Unlock()
	mock.ExportedMethodFunc()
}

// ExportedMethodCalls gets all the calls that were made to ExportedMethod.
// Check the length with:
//
//	len(mockedInterface2.ExportedMethodCalls())
func (mock *Interface2Mock) ExportedMethodCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockExportedMethod.RLock()
	calls = mock.calls.ExportedMethod
	mock.lockExportedMethod.RUnlock()
	return calls
}
