// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package withresets

import (
	"context"
	"sync"
)

// Ensure, that ResetStoreMock does implement ResetStore.
// If this is not the case, regenerate this file with moq.
var _ ResetStore = &ResetStoreMock{}

// ResetStoreMock is a mock implementation of ResetStore.
//
//	func TestSomethingThatUsesResetStore(t *testing.T) {
//
//		// make and configure a mocked ResetStore
//		mockedResetStore := &ResetStoreMock{
//			ClearCacheFunc: func(id string)  {
//				panic("mock out the ClearCache method")
//			},
//			CreateFunc: func(ctx context.Context, person *Reset, confirm bool) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*Reset, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedResetStore in code that requires ResetStore
//		// and then make assertions.
//
//	}
type ResetStoreMock struct {
	// ClearCacheFunc mocks the ClearCache method.
	ClearCacheFunc func(id string)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, person *Reset, confirm bool) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*Reset, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClearCache holds details about calls to the ClearCache method.
		ClearCache []struct {
			// ID is the id argument value.
			ID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Person is the person argument value.
			Person *Reset
			// Confirm is the confirm argument value.
			Confirm bool
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockClearCache sync.RWMutex
	lockCreate     sync.RWMutex
	lockGet        sync.RWMutex
}

// ClearCache calls ClearCacheFunc.
func (mock *ResetStoreMock) ClearCache(id string) {
	if mock.ClearCacheFunc == nil {
		panic("ResetStoreMock.ClearCacheFunc: method is nil but ResetStore.ClearCache was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = append(mock.calls.ClearCache, callInfo)
	mock.lockClearCache.Unlock()
	mock.ClearCacheFunc(id)
}

// ClearCacheCalls gets all the calls that were made to ClearCache.
// Check the length with:
//
//	len(mockedResetStore.ClearCacheCalls())
func (mock *ResetStoreMock) ClearCacheCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockClearCache.RLock()
	calls = mock.calls.ClearCache
	mock.lockClearCache.RUnlock()
	return calls
}

// ResetClearCacheCalls reset all the calls that were made to ClearCache.
func (mock *ResetStoreMock) ResetClearCacheCalls() {
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = nil
	mock.lockClearCache.Unlock()
}

// Create calls CreateFunc.
func (mock *ResetStoreMock) Create(ctx context.Context, person *Reset, confirm bool) error {
	if mock.CreateFunc == nil {
		panic("ResetStoreMock.CreateFunc: method is nil but ResetStore.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Person  *Reset
		Confirm bool
	}{
		Ctx:     ctx,
		Person:  person,
		Confirm: confirm,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, person, confirm)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedResetStore.CreateCalls())
func (mock *ResetStoreMock) CreateCalls() []struct {
	Ctx     context.Context
	Person  *Reset
	Confirm bool
} {
	var calls []struct {
		Ctx     context.Context
		Person  *Reset
		Confirm bool
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// ResetCreateCalls reset all the calls that were made to Create.
func (mock *ResetStoreMock) ResetCreateCalls() {
	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()
}

// Get calls GetFunc.
func (mock *ResetStoreMock) Get(ctx context.Context, id string) (*Reset, error) {
	if mock.GetFunc == nil {
		panic("ResetStoreMock.GetFunc: method is nil but ResetStore.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedResetStore.GetCalls())
func (mock *ResetStoreMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *ResetStoreMock) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ResetStoreMock) ResetCalls() {
	mock.lockClearCache.Lock()
	mock.calls.ClearCache = nil
	mock.lockClearCache.Unlock()

	mock.lockCreate.Lock()
	mock.calls.Create = nil
	mock.lockCreate.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}
