// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package typealiaspkgimport

import (
	"github.com/matryer/moq/pkg/moq/testpackages/typealiaspkgimport/alias"
	"sync"
)

// Ensure, that ProcessorMock does implement Processor.
// If this is not the case, regenerate this file with moq.
var _ Processor = &ProcessorMock{}

// ProcessorMock is a mock implementation of Processor.
//
// 	func TestSomethingThatUsesProcessor(t *testing.T) {
//
// 		// make and configure a mocked Processor
// 		mockedProcessor := &ProcessorMock{
// 			ProcessFunc: func(msg alias.Message) error {
// 				panic("mock out the Process method")
// 			},
// 		}
//
// 		// use mockedProcessor in code that requires Processor
// 		// and then make assertions.
//
// 	}
type ProcessorMock struct {
	// ProcessFunc mocks the Process method.
	ProcessFunc func(msg alias.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Process holds details about calls to the Process method.
		Process []struct {
			// Msg is the msg argument value.
			Msg alias.Message
		}
	}
	lockProcess sync.RWMutex
}

// Process calls ProcessFunc.
func (mock *ProcessorMock) Process(msg alias.Message) error {
	if mock.ProcessFunc == nil {
		panic("ProcessorMock.ProcessFunc: method is nil but Processor.Process was just called")
	}
	callInfo := struct {
		Msg alias.Message
	}{
		Msg: msg,
	}
	mock.lockProcess.Lock()
	mock.calls.Process = append(mock.calls.Process, callInfo)
	mock.lockProcess.Unlock()
	return mock.ProcessFunc(msg)
}

// ProcessCalls gets all the calls that were made to Process.
// Check the length with:
//     len(mockedProcessor.ProcessCalls())
func (mock *ProcessorMock) ProcessCalls() []struct {
	Msg alias.Message
} {
	var calls []struct {
		Msg alias.Message
	}
	mock.lockProcess.RLock()
	calls = mock.calls.Process
	mock.lockProcess.RUnlock()
	return calls
}
