// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package withrequirecalls

import (
	"errors"
	"sync"
)

// Ensure, that RequireCallsMock does implement RequireCalls.
// If this is not the case, regenerate this file with moq.
var _ RequireCalls = &RequireCallsMock{}

// RequireCallsMock is a mock implementation of RequireCalls.
//
//	func TestSomethingThatUsesRequireCalls(t *testing.T) {
//
//		// make and configure a mocked RequireCalls
//		mockedRequireCalls := &RequireCallsMock{
//			GetExampleFunc: func()  {
//				panic("mock out the GetExample method")
//			},
//			SetExampleFunc: func()  {
//				panic("mock out the SetExample method")
//			},
//		}
//
//		// use mockedRequireCalls in code that requires RequireCalls
//		// and then make assertions.
//
//	}
type RequireCallsMock struct {
	// GetExampleFunc mocks the GetExample method.
	GetExampleFunc func()

	// SetExampleFunc mocks the SetExample method.
	SetExampleFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// GetExample holds details about calls to the GetExample method.
		GetExample []struct {
		}
		// SetExample holds details about calls to the SetExample method.
		SetExample []struct {
		}
	}
	lockGetExample sync.RWMutex
	lockSetExample sync.RWMutex
}

// GetExample calls GetExampleFunc.
func (mock *RequireCallsMock) GetExample() {
	if mock.GetExampleFunc == nil {
		panic("RequireCallsMock.GetExampleFunc: method is nil but RequireCalls.GetExample was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetExample.Lock()
	mock.calls.GetExample = append(mock.calls.GetExample, callInfo)
	mock.lockGetExample.Unlock()
	mock.GetExampleFunc()
}

// GetExampleCalls gets all the calls that were made to GetExample.
// Check the length with:
//
//	len(mockedRequireCalls.GetExampleCalls())
func (mock *RequireCallsMock) GetExampleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetExample.RLock()
	calls = mock.calls.GetExample
	mock.lockGetExample.RUnlock()
	return calls
}

// SetExample calls SetExampleFunc.
func (mock *RequireCallsMock) SetExample() {
	if mock.SetExampleFunc == nil {
		panic("RequireCallsMock.SetExampleFunc: method is nil but RequireCalls.SetExample was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSetExample.Lock()
	mock.calls.SetExample = append(mock.calls.SetExample, callInfo)
	mock.lockSetExample.Unlock()
	mock.SetExampleFunc()
}

// SetExampleCalls gets all the calls that were made to SetExample.
// Check the length with:
//
//	len(mockedRequireCalls.SetExampleCalls())
func (mock *RequireCallsMock) SetExampleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSetExample.RLock()
	calls = mock.calls.SetExample
	mock.lockSetExample.RUnlock()
	return calls
}

// RequireCalls returns an error if any non-nil methods were not called.
// This is the inverse of "panic on nil method".
// It can be used to require that unused mocks are removed from tests.
//
// m := ExampleMock{ ExampleFunc: func(){}, OtherFunc: nil }
// someOtherFunction(m) // Doesn't call m.Example()
//
//	if err := m.RequireCalls(); err != nil{
//	    t.Errorf("All non-nil methods must be called: %s", err)
//	}
func (mock *RequireCallsMock) RequireCalls() error {
	if mock.GetExampleFunc != nil {
		mock.lockGetExample.Lock()
		defer mock.lockGetExample.Unlock()
		if len(mock.calls.GetExample) == 0 {
			return errors.New("RequireCallsMock.GetExample is non-nil but was never called")
		}
	}

	if mock.SetExampleFunc != nil {
		mock.lockSetExample.Lock()
		defer mock.lockSetExample.Unlock()
		if len(mock.calls.SetExample) == 0 {
			return errors.New("RequireCallsMock.SetExample is non-nil but was never called")
		}
	}
	return nil
}
