// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package two

import (
	"sync"

	"github.com/matryer/moq/pkg/moq/testpackages/imports/one"
)

var (
	lockDoSomethingMockAnother sync.RWMutex
	lockDoSomethingMockDo      sync.RWMutex
)

// Ensure, that DoSomethingMock does implement DoSomething.
// If this is not the case, regenerate this file with moq.
var _ DoSomething = &DoSomethingMock{}

// DoSomethingMock is a mock implementation of DoSomething.
//
//     func TestSomethingThatUsesDoSomething(t *testing.T) {
//
//         // make and configure a mocked DoSomething
//         mockedDoSomething := &DoSomethingMock{
//             AnotherFunc: func(thing one.Thing) error {
// 	               panic("mock out the Another method")
//             },
//             DoFunc: func(thing one.Thing) error {
// 	               panic("mock out the Do method")
//             },
//         }
//
//         // use mockedDoSomething in code that requires DoSomething
//         // and then make assertions.
//
//     }
type DoSomethingMock struct {
	// AnotherFunc mocks the Another method.
	AnotherFunc func(thing one.Thing) error

	// DoFunc mocks the Do method.
	DoFunc func(thing one.Thing) error

	// calls tracks calls to the methods.
	calls struct {
		// Another holds details about calls to the Another method.
		Another []struct {
			// Thing is the thing argument value.
			Thing one.Thing
		}
		// Do holds details about calls to the Do method.
		Do []struct {
			// Thing is the thing argument value.
			Thing one.Thing
		}
	}
}

// Another calls AnotherFunc.
func (mock *DoSomethingMock) Another(thing one.Thing) error {
	if mock.AnotherFunc == nil {
		panic("DoSomethingMock.AnotherFunc: method is nil but DoSomething.Another was just called")
	}
	callInfo := struct {
		Thing one.Thing
	}{
		Thing: thing,
	}
	lockDoSomethingMockAnother.Lock()
	mock.calls.Another = append(mock.calls.Another, callInfo)
	lockDoSomethingMockAnother.Unlock()
	return mock.AnotherFunc(thing)
}

// AnotherCalls gets all the calls that were made to Another.
// Check the length with:
//     len(mockedDoSomething.AnotherCalls())
func (mock *DoSomethingMock) AnotherCalls() []struct {
	Thing one.Thing
} {
	var calls []struct {
		Thing one.Thing
	}
	lockDoSomethingMockAnother.RLock()
	calls = mock.calls.Another
	lockDoSomethingMockAnother.RUnlock()
	return calls
}

// Do calls DoFunc.
func (mock *DoSomethingMock) Do(thing one.Thing) error {
	if mock.DoFunc == nil {
		panic("DoSomethingMock.DoFunc: method is nil but DoSomething.Do was just called")
	}
	callInfo := struct {
		Thing one.Thing
	}{
		Thing: thing,
	}
	lockDoSomethingMockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	lockDoSomethingMockDo.Unlock()
	return mock.DoFunc(thing)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedDoSomething.DoCalls())
func (mock *DoSomethingMock) DoCalls() []struct {
	Thing one.Thing
} {
	var calls []struct {
		Thing one.Thing
	}
	lockDoSomethingMockDo.RLock()
	calls = mock.calls.Do
	lockDoSomethingMockDo.RUnlock()
	return calls
}
